Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,9 @@ jobs:
           fi
 
       - name: Install Dependencies
-        run: npm install
+        run: |
+          npm install
+          npm install expo @expo/cli --save-dev --legacy-peer-deps
 
       - name: Setup Java JDK
         uses: actions/setup-java@v4
@@ -37,13 +39,13 @@ jobs:
 
       - name: Build Android APK
         run: |
-          npx expo prebuild --platform android || true
+          npx expo prebuild --platform android --clean || true
           if [ -d "android" ]; then
             cd android
             chmod +x gradlew
             ./gradlew assembleRelease
           else
-            echo "No android folder generated."
+            echo "Failed to generate android directory"
             exit 1
           fi
 
